# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrapper.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wrapper.proto',
  package='wrapper',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rwrapper.proto\x12\x07wrapper\"\xae\x01\n\x0b\x41uthWrapper\x12\x0f\n\x07pub_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x34\n\x06scheme\x18\x03 \x01(\x0e\x32$.wrapper.AuthWrapper.SignatureScheme\x12\x1a\n\x12serialized_payload\x18\x04 \x01(\x0c\")\n\x0fSignatureScheme\x12\x0b\n\x07SCHNORR\x10\x00\x12\t\n\x05\x45\x43\x44SA\x10\x01\x62\x06proto3'
)



_AUTHWRAPPER_SIGNATURESCHEME = _descriptor.EnumDescriptor(
  name='SignatureScheme',
  full_name='wrapper.AuthWrapper.SignatureScheme',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCHNORR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ECDSA', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=160,
  serialized_end=201,
)
_sym_db.RegisterEnumDescriptor(_AUTHWRAPPER_SIGNATURESCHEME)


_AUTHWRAPPER = _descriptor.Descriptor(
  name='AuthWrapper',
  full_name='wrapper.AuthWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='wrapper.AuthWrapper.pub_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='wrapper.AuthWrapper.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scheme', full_name='wrapper.AuthWrapper.scheme', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialized_payload', full_name='wrapper.AuthWrapper.serialized_payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUTHWRAPPER_SIGNATURESCHEME,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=201,
)

_AUTHWRAPPER.fields_by_name['scheme'].enum_type = _AUTHWRAPPER_SIGNATURESCHEME
_AUTHWRAPPER_SIGNATURESCHEME.containing_type = _AUTHWRAPPER
DESCRIPTOR.message_types_by_name['AuthWrapper'] = _AUTHWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthWrapper = _reflection.GeneratedProtocolMessageType('AuthWrapper', (_message.Message,), {
  'DESCRIPTOR' : _AUTHWRAPPER,
  '__module__' : 'wrapper_pb2'
  # @@protoc_insertion_point(class_scope:wrapper.AuthWrapper)
  })
_sym_db.RegisterMessage(AuthWrapper)


# @@protoc_insertion_point(module_scope)
